{{- $root := . }}
  {{- range $name, $values := .Values.app.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "primeapps.name" $ }}-studio-{{ $name | lower }}
data:
  {{- range $key, $value := $values }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
---
{{- end }}