rbac:
   create: true
ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - functions-test.primeapps.io
  tls:
   - secretName: functions-test-tls
     hosts:
       - functions-test.primeapps.io