---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-app-preview-config
  namespace: primeapps
data:
  TenantDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=prod;command timeout=0;keepalive=30;maximum pool size=1000;"
  PlatformDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;maximum pool size=1000;"
  RedisConnection: "cache-redis-master.cache:6379,password=pr!m€Appsi0r,defaultDatabase=1,syncTimeout=30000"
  AuthenticationServerURL: "https://auth-preview.primeapps.io"
  StorageUrl: "https://storage-pde.primeapps.io"
  StorageAccessKey: "47059d03d1224a4505c517aaca18ef55"
  StorageSecretKey: "998321ed439a32dfc364b4e9884e9879"
  EnableJobs: "true"
  EnableRequestLogging: "false"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  ClientId: "primeapps_preview"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  GoogleMapsApiKey: "AIzaSyDxai8Lo5_z03O9am5WyP5XvYtITzC_l-o"
  AsposeLicence: ""
  PreviewMode: "app"
  PreviewClient: "primeapps_preview"
  StudioUrl: "https://studio.primeapps.io"
  SentryDsn: "https://9f004ecf59ff428a8a980b8684ca8aa4:b2332eb76fca4866b48d421dad70ea5c@log.primeapps.io/5"
---
apiVersion: v1
data:
  aspnetapp.pfx: MIIHagIBAzCCBzAGCSqGSIb3DQEHAaCCByEEggcdMIIHGTCCBg8GCSqGSIb3DQEHBqCCBgAwggX8AgEAMIIF9QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI5ztBkNuoYRgCAggAgIIFyKDgGY37nqdtDDutz4xz5rxwyHizzOHyyi5E2q+NzOkeXVddPVnjc/0+9EWFzGk7+XX0OeT/v6l96E6+p2LFdfadnyBLrrDQm0yYeA51Ty8rh3pEnHo/3lbFpfmwAC3f1R+UFV+uRnmjyCs58/en9cKF1KCpHSNnBU9nDQHLxg4epiV7gIdSRof/o7xsi8i+oCsALAsTFCoA1vPWavATxoU78o/oAtH4KZMvvzW+emHNAfn9sm9dWNB1s0D9frzM3bwBSUisXLfYtTNqnG8ftI0SzEJu+NgdRNRSoO92slNDemYRK4kXB5k4lnAqH7eg+ui3HnpBTfCnbEpv+MClLvMCdPxwN7llMiv+mFm+TwwyvqMnu7r754pCvnL8qh08aP5G2+Wd29RlvlpHZCn3nYptuQUz87/biONZTQQIgbaaLROUY8ujnlLZvJ2yEo28Y+rkH44zeuIzNtLsNQcLN/BvZmRllTRQPxv3NX201qC711kIgAgVQRCSOBGVWzM9zl7/s1S5tW2/cQJGLyyGUT0qpFUGTJpJkbG9JC5iYepJxc9pyhYXevd4vQMyKUJ80iobuN7LCg+BTSBwAeXK8ds50qB3kPrwU8L3Xq/CiNfXrTYO/ghJ28y2jyLZSFYmEIs5Zff4hf8nMyHnXaalP7npvASHPr7qoHYQUeBxlwnqOGFFHvevGR5jNOhbkCVq/f77tW/N/qMWVf0c4yRiGRt8T1cemU4RuG5He6qthJoh3jHTf9gT2pXrGJI0Y0ZdOit3rie/RNTQwTfdtNki1lNF2QnnsOLvb5a+hTaDG2uktVIqHRfut3+8yw0C26K5ZouJXVDA/1RIdY1d/YMAk2PtKnDkbCtEvp6nE/ipQQ9GA8pBlbwWNSETGCRaWMt8wbfojeNtSMEc9BCV+QZz6/F7/70e0ECL9RgoYZzgpBXpeZteJEwuHT79mfrW/67nN5d3ZT1zKoVp3uR3+11iZDoRCB79adGt7yVyzmumIj+KzgTrPlyl9nii8xU6xEe1hZrCD24mysydjsFnws6qD4dWtwPFP7tLQdELKlsT8P2j8RJRNpZFG7zMqXfL2syBsYNer7ocVHFxjmjremjK4KyhV1IuCGNleWqvALAMM2yBgD0Fo5QekQNJJWrvVLWeoR/x9W7s5LCw/yCOYg0119w2NLD1KSRxXWmQapwC7pikuBB0QP+YndxzfctSGZ2RlO/WwKJQviAWh/OEDpSqtyXA/jjNprGtCwauGrdNmw4GBRqlsIlrMx7bKGah2yuFmjq1nqcScPeNhi/sySjGgRwKAerpEFAlftHJIm6bH8ah6HaSpxwZKOL/0zepXsoLuIAF7xNH0E3ky3n9ZiVOdjj5t8FBioGYWEEltmWP5Qiq0igrFvHy8DJrZk8q5xx/gBgBQpyrjPi5p+svu52nj3mVJruadtdcdTytIQN+L8OO2ww9vP8bHFbWEhQXi89USNPX/1nZCnCFuWyfO7l0qW4CWHXw9b+wH22nqE/eVqKh2lpgUgoVDVg9A7EzDdfgXemZ8+5N8Uq/3Yh0A8RYIFP4/D1hqrBG67V49Z7QavdAn//YCL86daal+OB9QZRraMhpstll031lNMuCQzk8UHsJMXZtEUdM8w8GaHGBmIfeKX197sgDwMNRLm7kpWaEjAipFz6HvFwRG+QEZb9QinW0/Kby1cV2Bsez0C8t+mJ3ukySTNukQkEJa1EmVN4mL19kpMGilZ+X2cad1NnvUDc2IRDgRz3wrU7LtLStgZ0y5jMGHVljbmKZJJSd97LwW/j8K6Vle0IXcEj9hizCovRkA0aS1jLxU4hw+RZkljjkRX5yiIG5FQGwVRmHYtBv2Hn5cHZ6eHiQZuzEefpA1r0SI61vji86ZEty9nOmLUI4iaw4JWNR2WQQjHQPxRwqN1Vhg7SaQBdbUzS0R/6PUSJ9du7XLTJ2Bahi8fCt1VmPDMTfgfYvvC8wggECBgkqhkiG9w0BBwGggfQEgfEwge4wgesGCyqGSIb3DQEMCgECoIG0MIGxMBwGCiqGSIb3DQEMAQMwDgQIpbPeAddMHegCAggABIGQOXiYWJcGm0NUE3ByQdf59vCbgSZ/XLSlumRbEBP5AtDSxEMqSu8zQSAR/sFCGtY+JaUtdeYgl6Z4YqcitMEd8vmaETQKPbMyMAMGHjbPR+nt1MvlBbBecHoA2fDmLJEHh+ViKCcoXydX8/Ey0/y46ahIyY8B/ikFOYIwotZRQPS3EvDAHIRW23lDg4XR3AbnMSUwIwYJKoZIhvcNAQkVMRYEFAo8K6JYztV3i1SwyZEU3swdCveHMDEwITAJBgUrDgMCGgUABBT13hCsSn/9phPkn20veTS+55caFgQIpTVglnzdKuUCAggA
kind: Secret
metadata:
  name: primeapps-app-preview-selfsigned-ssl
  namespace: primeapps
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-app-preview
  namespace: primeapps
  labels:
    k8s-app: "primeapps-app-preview"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: primeapps-app-preview
  template:
    metadata:
      labels:
        k8s-app: primeapps-app-preview
    spec:
      volumes:
        - name: "self-signed-ssl"
          secret:
            secretName: primeapps-app-preview-selfsigned-ssl      
      containers:
        - name: primeapps-app-preview
          image: primeapps/primeapps-app:1.19.132.2-debian
          env:
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: RedisConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EnableJobs
            - name: AppSettings__EnableRequestLogging
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EnableRequestLogging
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPPassword
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: HttpsRedirection
            - name: AppSettings__GoogleMapsApiKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: GoogleMapsApiKey
            - name: AppSettings__AsposeLicence
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: AsposeLicence                  
            - name: AppSettings__PreviewMode
                valueFrom:
                  configMapKeyRef:
                    name: primeapps-app-preview-config
                    key: PreviewMode
            - name: AppSettings__PreviewClient
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: PreviewClient
            - name: AppSettings__StudioUrl
                valueFrom:
                  configMapKeyRef:
                    name: primeapps-app-preview-config
                    key: StudioUrl
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: SentryDsn              
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-app-preview-service
  namespace: primeapps
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-app-preview
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-app-preview-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/server-snippet: |-
      add_header X-Robots-Tag "noindex, nofollow";
spec:
  tls:
    - hosts:
        - preview.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: preview.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-app-preview-service
              servicePort: 80
