---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-studio-config
  namespace: primeapps
data:
  TenantDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=prod;command timeout=0;keepalive=30;maximum pool size=1000;"
  PlatformDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;maximum pool size=1000;"
  StudioDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=studio;command timeout=0;keepalive=30;maximum pool size=1000;"
  RedisConnection: "cache-redis-master.cache:6379,password=pr!m€Appsi0r,defaultDatabase=1,syncTimeout=30000"
  StorageUrl: "https://storage-pde.primeapps.io"
  StorageAccessKey: "47059d03d1224a4505c517aaca18ef55"
  StorageSecretKey: "998321ed439a32dfc364b4e9884e9879"
  StorageUrlProd: "https://storage.primeapps.io"
  EnableJobs: "true"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  AuthenticationServerURL: "https://auth.primeapps.io"
  ClientId: "primeapps_studio"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  PreviewUrl: "https://preview.primeapps.io"
  KubernetesClusterRootUrl: "https://test-5f8a7238.hcp.francecentral.azmk8s.io"
  KubernetesClusterAccessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJla3MtYWRtaW4tdG9rZW4ta2ZxcGciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWtzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWNjODkyYjctNTRmZC0xMWU5LWFkZDMtMDYxMmIxOTc5YjIwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmVrcy1hZG1pbiJ9.j3rAlfrkjPiJxcleefpCF1P2E8oQNwvLe8ymW8sR_9N7QkTRRkyHLYVkvbGIL2gj-gzZ3itBeKoQ417VFn5LcybeE216ixxfHRIErnXZrTuatspSrIPM6D27VaBmUZLbYLkLZBW0SBKx0SBy8bJVmSu1LmiI-46d9cit4zmBZRYfrX0-WWq4uU0HUgo8D36dA5LC6_nnJ3xzbMs5VeyLPc3Z3UhQoDExcmxWUBDsbf3rvFQ85mj5rxXW0Y0JiHAHVKxKFrp3qidjlnikvFIZ905mpAyqmZksVZm4IOj5axX1gZ4eGLJRxPxrskNBZRM8PeAKxM6Gj1G8qgzkgj6b_Q"
  GiteaEnabled: "true"
  GiteaUrl: "https://git.primeapps.io"
  GiteaEmail: "primeapps"
  GiteaPassword: "pr!m€Appsi0g"
  PostgresPath: "/usr/bin"
  DataDirectory: "/data"
  AppUrl: "{0}.primeapps.app"
  SentryDsn: "https://a6d7a462d9184c5698ab07aa38b8a896:a915b64d63574d29b98998a69cbdc848@log.primeapps.io/2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: primeapps-studio
  namespace: primeapps
  labels:
    k8s-app: "primeapps-studio"
  annotations:
    volume.alpha.kubernetes.io/storage-class: gp2
    failure-domain.beta.kubernetes.io/zone: eu-west-1c
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: primeapps-docker-hub
  namespace: primeapps
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwcmltZWFwcHNhZG1pbiIsInBhc3N3b3JkIjoicHIhbeKCrEFwcHNpMGQiLCJlbWFpbCI6ImFkbWluQHByaW1lYXBwcy5pbyIsImF1dGgiOiJjSEpwYldWaGNIQnpZV1J0YVc0NmNISWhiZUtDckVGd2NITnBNR1E9In19fQ==
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-studio
  namespace: primeapps
  labels:
    k8s-app: "primeapps-studio"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: primeapps-studio
  template:
    metadata:
      labels:
        k8s-app: primeapps-studio
    spec:
      volumes:
        - name: studio-data-volume
          persistentVolumeClaim:
            claimName: studio-data-volume-claim
      imagePullSecrets:
        - name: primeapps-docker-hub
      containers:
        - name: primeapps-studio
          image: primeappsadmin/primeapps-studio:1.19.132.2
          volumeMounts:
            - mountPath: "/data"
              name: studio-data-volume
          env:
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__StudioDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StudioDBConnection
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: RedisConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EnableJobs
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPassword          
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: HttpsRedirection
            - name: AppSettings__PreviewUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PreviewUrl
            - name: AppSettings__KubernetesClusterRootUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterRootUrl
            - name: AppSettings__KubernetesClusterAccessToken
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterAccessToken
            - name: AppSettings__GiteaEnabled
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEnabled
            - name: AppSettings__GiteaUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaUrl
            - name: AppSettings__GiteaEmail
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEmail
            - name: AppSettings__GiteaPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaPassword
            - name: AppSettings__PostgresPath
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PostgresPath
            - name: AppSettings__DataDirectory
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: DataDirectory
            - name: AppSettings__AppUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: AppUrl            
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-studio-service
  namespace: primeapps
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-studio
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-studio-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |-
      add_header X-Robots-Tag "noindex, nofollow";
spec:
  tls:
    - hosts:
        - studio.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: studio.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-studio-service
              servicePort: 80
