# Default values for PrimeApps
environment: kubernetes
app:
  serviceType: NodePort
  servicePort: 80
  servicePortSecure: 443
  containerPort: 80
  containerPortSecure: 443
  component: app
  replicas: 1
  image: eu.gcr.io/primeapps-gke/primeapps-app
  imageTag: master
  imagePullPolicy: Always
  pullsecret: container-registry-secret
  cpu: 10m
  memory: 256Mi
  ingress:
    enabled: true
    hostname: test.primeapps.io
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      # kubernetes.io/tls-acme: "true"
    tls: true
  probes:
    enabled: false
  secrets:
    ConnectionStrings:
      TenantDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=dev;command timeout=0;keepalive=30;"
      PlatformDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=platform;command timeout=0;keepalive=30;"
      RedisConnection: "redis-dev.primeapps.io:6379,password=pr!m€Apps!0D€v,defaultDatabase=1"
    AppSettings:
      StorageUrl: "http://storage.okd.primeapps.io"
      StorageAccessKey: "ofisim-storage"
      StorageSecretKey: "veryHiddenSecretNoOneCanGuess:O"
      EnableJobs: "true"
      FunctionUrl: "http://localhost:7071"
      EmailSMTPEnableSsl: "true"
      EmailSMTPHost: "smtp.mailtrap.io"
      EmailSMTPPort: "465"
      EmailSMTPUser: "b12c70f7f50ca9"
      EmailSMTPPassword: "2cfb87c728981a"
      UseCdn: "false"
      AuthenticationServerURL: "https://auth-dev.primeapps.io"
      ClientId: "primeapps"
      ClientSecret: "secret"
      ForwardHeaders: "true"
      HttpsRedirection: "true"
      TestMode: "true"
      PreviewMode: "tenant"
    Sentry:
      Dsn: "https://494e887684744adfaa39328e539a2a95@sentry-dev.primeapps.io/3"
      IncludeRequestPayload: "true"
      IncludeActivityData: "true"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
auth:
  serviceType: NodePort
  servicePort: 80
  servicePortSecure: 443
  containerPort: 80
  containerPortSecure: 443
  component: auth
  replicas: 1
  image: eu.gcr.io/primeapps-gke/primeapps-auth
  imageTag: master
  imagePullPolicy: Always
  ##Secrets
  pullsecret: container-registry-secret
  cpu: 10m
  memory: 256Mi
  ## Ingress settings
  ingress:
    enabled: true
    hostname: auth-test.primeapps.io
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    tls: true
  probes:
    enabled: false
  secrets:
    ConnectionStrings:
      AuthDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=auth;command timeout=0;keepalive=30;"
      TenantDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=dev;command timeout=0;keepalive=30;"
      PlatformDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=platform;command timeout=0;keepalive=30;"
    AppSettings:
      Authority: "https://auth-dev.primeapps.io"
      ForwardHeaders: "true"
      HttpsRedirection: "true"
      AuthCertLocation: "/cert/primeapps_id4.pfx"
      AuthCertExportKey: "1q2w3e4r5t"
    Sentry:
      Dsn: "https://72fdb461a2344589bad128b3cd2d135a@sentry-dev.primeapps.io/5"
      IncludeRequestPayload: "true"
      IncludeActivityData: "true"