web:
  replicacount: 1
cron:
  replicacount: 1
worker:
  replicacount: 1
user:
  create: true
  email: teknik@ofisim.com
  password: 'pr!meApps!0'
email:
  from_address: teknik@ofisim.com
  host: smtp.office365.com
  port: 587
  use_tls: true
  user: teknik@ofisim.com
  password: '0f!s!mCRM'
  enable_replies: false
persistence:
  enabled: true
  storageClass: "gp2"
  accessMode: ReadWriteOnce
  size: 8Gi
ingress:
  enabled: true
  hostname: sentry-prod.primeapps.io
annotations:
  kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: 'true'
tls:
   - secretName: sentry-prod.primeapps.io
     hosts:
       - sentry-prod.primeapps.io
postgresql:
  host: pre.database.svc.cluster.local
  user: postgres
  password: 'pr!meApp$!0'
  database: sentry
redis:
  host: cache-redis-master.cache.svc.cluster.local
  password: 'pr!meApps!0'