web:
  replicacount: 1
cron:
  replicacount: 1
worker:
  replicacount: 1
  env:
  - name: C_FORCE_ROOT
    value: "true"
user:
  create: true
  email: teknik@ofisim.com
  password: 'pr!meApps!0'
email:
  from_address: teknik@ofisim.com
  host: smtp.office365.com
  port: 587
  use_tls: true
  user: teknik@ofisim.com
  password: '0f!s!mCRM'
  enable_replies: false
persistence:
  enabled: true
  storageClass: "gp2"
  accessMode: ReadWriteOnce
  size: 8Gi
postgresql:
  host: "primeapps.database.svc"
  user: "postgres"
  password: "aJBzfMe40N"
  database: "sentry"
redis:
  host: "redis-master.cache.svc"
  password: 'pr!meApps!0'