---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-auth-preview-config
  namespace: primeapps
data:
  AuthDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=auth;command timeout=0;keepalive=30;"
  TenantDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=prod;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;"
  Authority: "https://auth-preview.primeapps.io"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  ValidationSkipDomains: "auth-preview.primeapps.io;"
  StudioUrl: "https://studio.primeapps.io"
  GiteaEnabled: "true"
  GiteaUrl: "https://git.primeapps.io"
  PreviewMode: "app"
  SentryDsn: "https://32c686fef4c04dfaa277ebdd2181b908:0b11aad57b8847f0b213be197bb85c2b@log.primeapps.io/6"
---
apiVersion: v1
data:
  aspnetapp.pfx: MIIHagIBAzCCBzAGCSqGSIb3DQEHAaCCByEEggcdMIIHGTCCBg8GCSqGSIb3DQEHBqCCBgAwggX8AgEAMIIF9QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIb7VauqkVjr0CAggAgIIFyOpA7H3MEFCK0qJNaihYDj/JGQevhMCxQEMfz4nqnd30vlmwm7IeQix0b9alOxKOztF7g/Tj42fFC8nvJkwy8VSOBiYwJCJtWJrirq+/ffqnZ6MQz54QY3SNEj2uDtgU4ifvHOYBq5XsoqGMT7drlo1nRkBO7z+IreguaXVrAWDVRvwGJnDVHDZfmA6l+9jXGxz5zam5JgKTWkkDpqA6NskKbkUtvl7+v0SRfT7eHtUgtjqZBDa6Gi8KnUnRVS3BS5TqKDe4ZtQUi+KH2H83mX2rrWHQpZHIB2215+oBN1thirJyzEGznkkznXLxOkujE5gFnm/Xe+b2WBzKokpFrMJ5Odzp5/jQvKDOzoKva/C//9RoCvtzGq3rD8qXJhLAllQdopTR6YNE1EjJ7OqsFeK6Db5/2GJVm3VCr5q4zqYT29/fjGgBT3l/xKRDnzbp2uEBvfL/Suk6qSEUgYOCdTXcb0lTeYDqD/reKC+QZiGPJp0fLeDW4xkpOi5+1tKR5MvxY0is5cOW/CkQ/0Q/c5/f9aTTgNrcKyEgILq7a8I2bjmdMPqB9qkqOVjm+lnQkueWhlzJmjdY9wbH7yy+nVyeiIhLx0IlUWpnkUe+jck76vTQ9h1NDIUN31fPvPfutOXzDc1KIc/2uq6399RPhpcLyG8cKA2ZnSsij5axqDpDltZyzQYCyQ7uBs4qcaJo4UKFCIdHr5A3+ETGMxTILkO7evGzPaNoOzfErJ1eViV/PJUwzJzfCcmu/Ng6CwI3uUE7KJhaZ8mtD3mrkAp2TmOAysSgqrzXTRMUzdsCDB5IoO84vR7Zs2z9SaUL7mtBy5NGkxGZssQrQ3+0pwlIo2KZ+eMIkbHJme9dPiR8Xpdi3xBlMY8rnbix5d72EET7VXj9baQniLx6unwWSoAbverg5lHvS5zE+lFWedWpwprCBxD4slG2Dti7WhVw6Doc3gUePsBj4uDfqk0N23z/yu8BCMzTEDxBdqBcAWgnZy44bCf9/vjLX/EIX2uSC6fMWSHM64nvkjEhGGZnrPTjb5siXMSXxF0/Km5TyfcG1haF3VL8cELrKj0invczRwFk9VFoVPh6Uo/dCwXEQsINLJWRDdS+6cIjGrXU5QiM50VRWxPohSuXtNKSl80B2bIktdkSwOH43ymDaAeC3t0NrDNwGIfg0ft31uGTgv03Fjit62FUz/dkFFl1in48RTJxFmB8o9ZxaqQ0/NNAZz/t/EcjQ8qg2LJt915lAJY2m1uSMx7mqs8NbXCsxEH3B7078xf/oatnY4VfihTCNGoI32u93Ci1D5tY8hOxBd7Wls+UpKm8EcvdW2/mciAz8dLXqXnk5EQB8W7NhXx/eCY7oL5pUbyCofdJMuL5VoKUf+3iVL0nv5P78/ABvU81slSBL/M3Y2iS11+Dn5tlAinPYzUYtlGhOxP3SF3q2NLd8x4tdPpTuYjH8b1xsma+IjV61vAc4m4af/vU8RBQSnEVp0IiUXkFx6lMZ4fNDQB6bXtAJblPsWBWgBwuawNW7VTPL4oCWoJtV08m37ehOu0g37EyR+9U0SjpGBWI7RJwz47u+5RZdIRMSKEWr2Rt7XzCkGkNr0qSZ9RfsL8pc5H+p8ifU0foXmiqSHBIO3dZrVbk9VOBa+Rc5CyWsjF+RuisiudX3RtXCtT+hOx+JQ7BGuSHwiaTDm014bglH1nMApNR6cn5AUhQeLUn+7NAX9gqh87h1jyxFYCP+j+O0YEuKtJKiBAveshETgPL9d2vSmeQRlSLxWQBUMWnbWASI8+VIqCv4vkXgphnEES3poOv0fvPpIf+R9sOpff2ICXTydsuDKazXfH2Q2EBc0W6iWvLLZJoGAzLVst5ey6Xh2tzydSKb/IFnWzz2CWtRcGVBgIe70eoPsvzubvpoq2mRh0P+FPYXYChoaiErMpUvqHBS1DKmSnTXq7Mmx8qo1PrGrj3+CRo/XiDbT4wggECBgkqhkiG9w0BBwGggfQEgfEwge4wgesGCyqGSIb3DQEMCgECoIG0MIGxMBwGCiqGSIb3DQEMAQMwDgQIsYMnk/7ZolsCAggABIGQLij3Us24RcI8h3lFucYouMa/6AcuBLLiTbUmVwWWGiZwqzPHUSso1Kc8gkd/EAirJCMyj3BE9Q6kaf56BQb4SbzX/N0ucG35MUadSVO+qhWxgmSHpWPV4y0QmBEJQOSZ3WKNIC+EeYPaog1KqQGytcIqrlRDN1vw9PVpB+dg7/gcewWCaOATrY7HBPyoqt4HMSUwIwYJKoZIhvcNAQkVMRYEFGJ9VhFpHLkIbCxDUmMGhH3uRrCUMDEwITAJBgUrDgMCGgUABBR64gM6jKSFo0h0sn31j+g6gbGwSgQIv8PINqFPiz4CAggA
kind: Secret
metadata:
  name: primeapps-auth-preview-selfsigned-ssl
  namespace: primeapps
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-auth-preview
  namespace: primeapps
  labels:
    k8s-app: "primeapps-auth-preview"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: primeapps-auth-preview
  template:
    metadata:
      labels:
        k8s-app: primeapps-auth-preview
    spec:
      volumes:
        - name: "self-signed-ssl"
          secret:
            secretName: primeapps-auth-preview-selfsigned-ssl      
      containers:
        - name: primeapps-auth-preview
          image: primeapps/primeapps-auth:1.19.132.2-debian
          env:
            - name: ConnectionStrings__AuthDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: AuthDBConnection
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: PlatformDBConnection
            - name: AppSettings__Authority
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: Authority
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: HttpsRedirection
            - name: AppSettings__ValidationSkipDomains
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: ValidationSkipDomains
            - name: AppSettings__StudioUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: StudioUrl
            - name: AppSettings__GiteaEnabled
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: GiteaEnabled
            - name: AppSettings__GiteaUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: GiteaUrl
            - name: AppSettings__PreviewMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: PreviewMode
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-preview-config
                  key: SentryDsn
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1                  
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-auth-preview-service
  namespace: primeapps
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-auth-preview
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-auth-preview-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/server-snippet: |-
      add_header X-Robots-Tag "noindex, nofollow";
spec:
  tls:
    - hosts:
        - auth-preview.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: auth-preview.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-auth-preview-service
              servicePort: 80
