# Default values for PrimeApps
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
  # name: value
app:
  serviceType: NodePort
  servicePort: 80
  servicePortSecure: 443
  containerPort: 80
  containerPortSecure: 443
  component: app
  replicas: 1
  image: eu.gcr.io/primeapps-gke/primeapps-app
  imageTag: master
  imagePullPolicy: Always
  ##Secrets
  pullsecret: container-registry-secret
  cpu: 10m
  memory: 256Mi
  ## Ingress settings
  ingress:
    enabled: true
    hostname: dev.primeapps.io
    annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
    tls: true
  probes:
    enabled: false
  secrets:
      ConnectionStrings:
        AuthDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=auth;command timeout=0;keepalive=30;"
        TenantDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=dev;command timeout=0;keepalive=30;"
        PlatformDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=platform;command timeout=0;keepalive=30;"
        WarehouseConnection: "Server=tcp:ofisim-dwh-dev.database.windows.net,1433;Database=master;User ID=ofisim;Password=0f!s!mDev;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        StorageConnection: "http://51.144.165.200:9000"
        ElasticConnection: "http://es-dev.primeapps.io:9200/"
      AppSettings:
        EnableJobs: "true"
        AllowInsecureHttp: "true"
        StorageAccessKey: "ofisim-storage"
        StorageSecretKey: "veryHiddenSecretNoOneCanGuess:O"
        TestMode: "true"
        BlobUrl: "http://file-dev.ofisim.com"
        FunctionUrl: "http://localhost:7071"
        EmailSMTPEnableSsl: "true"
        EmailSMTPHost: "smtp.sendgrid.net"
        EmailSMTPPort: "587"
        EmailSMTPUser: "apikey"
        EmailSMTPPassword: "password"
        EmailSMTPHostTest: "smtp.mailtrap.io"
        EmailSMTPPortTest: "465"
        EmailSMTPUserTest: "b12c70f7f50ca9"
        EmailSMTPPasswordTest: "2cfb87c728981a"
        WarehouseServer: "ofisim-dwh-dev.database.windows.net"
        WarehouseMasterUser: "ofisim"
        WarehouseMasterPassword: "0f!s!mDev"
        PowerbiAccessKey: "n+3uhoGPMk7fCEB7J+ThW1vVE+1XJDQsHzkUbn0KJZ+tcqVmobO0XmIhKvis4tkOlwhfWALsI6o4dPGzYN+nIA=="
        PowerbiWorkspaceCollection: "OfisimDev"
        AzureStorage.ConnectionString: "DefaultEndpointsProtocol=https;AccountName=ofisimcomdev;AccountKey=uFQDgZlv6UVtP9Lbq3zOjiXC5pm8riBL3BVum1nHojQPL8AI+iYCj9x2HBypqXJ0yXhy0rAqNLjIZxydQblRwA==;"
        AzureSearch.Storage: "ofisimdev"
        AzureSearch.AdminKey: "044D958A74716C3622C6977E47AA3FEE"
        UseCdn: "false"
        AuthenticationServerURL: "https://auth-dev.primeapps.io"
        ClientId: "primeapps"
        ClientSecret: "secret"
        RequireHttps: "true"
        ForwardHeaders: "true"
        HttpsRedirection: "true"
      webOptimizer:
        enableCaching: "false"
        enableMemoryCache: "false"
        enableDiskCache: "false"
        cacheDirectory: "/var/temp/weboptimizercache"
        enableTagHelperBundling: "false"
      Sentry:
        Dsn: "https://494e887684744adfaa39328e539a2a95@sentry-dev.primeapps.io/3"
        IncludeRequestPayload: "true"
        IncludeActivityData: "true"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
auth:
  serviceType: NodePort
  servicePort: 80
  servicePortSecure: 443
  containerPort: 80
  containerPortSecure: 443
  component: auth
  replicas: 1
  image: eu.gcr.io/primeapps-gke/primeapps-auth
  imageTag: master
  imagePullPolicy: Always
  ##Secrets
  pullsecret: container-registry-secret
  cpu: 10m
  memory: 256Mi
  ## Ingress settings
  ingress:
    enabled: true
    hostname: auth-dev.primeapps.io
    annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
    tls: true
  probes:
    enabled: false
  secrets:
      ConnectionStrings:
        AuthDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=auth;command timeout=0;keepalive=30;"
        TenantDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=dev;command timeout=0;keepalive=30;"
        PlatformDBConnection: "server=pg-dev.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=platform;command timeout=0;keepalive=30;"
        WarehouseConnection: "Server=tcp:ofisim-dwh-dev.database.windows.net,1433;Database=master;User ID=ofisim;Password=0f!s!mDev;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        StorageConnection: "http://51.144.165.200:9000"
        ElasticConnection: "http://es-dev.primeapps.io:9200/"
      AppSettings:
        AuthCertLocation: "/cert/primeapps_id4.pfx"
        AuthCertExportKey: "1q2w3e4r5t"
        PublicOrigin: "https://auth-dev.primeapps.io"
        ValidUrls: "localhost;primeapps.io"
        ForwardHeaders: "true"
        HttpsRedirection: "true"
      webOptimizer:
        enableCaching: "false"
        enableMemoryCache: "false"
        enableDiskCache: "false"
        cacheDirectory: "/var/temp/weboptimizercache"
        enableTagHelperBundling: "false"
      Sentry:
        Dsn: "https://72fdb461a2344589bad128b3cd2d135a@sentry-dev.primeapps.io/5"
        IncludeRequestPayload: "true"
        IncludeActivityData: "true"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

