---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-app-config-test
  namespace: primeapps
data:
  TenantDBConnection: "server=pre-test.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=test;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=pre-test.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;"
  RedisConnection: "cache-test-redis-master.cache:6379,password=pr!m€Appsi0r,defaultDatabase=1"
  StorageUrl: "https://storage-test.primeapps.io"
  StorageAccessKey: "47059d03d1224a4505c517aaca18ef55"
  StorageSecretKey: "998321ed439a32dfc364b4e9884e9879"
  EnableJobs: "true"
  EnableBpm: "true"
  EnableRequestLogging: "false"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  AuthenticationServerURL: "https://auth-test.primeapps.io"
  ClientId: "primeapps_app"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  TestMode: "true"
  GoogleMapsApiKey: "AIzaSyDxai8Lo5_z03O9am5WyP5XvYtITzC_l-o"
  SentryDsn: "https://6689a455217f446994a756650c03014e:95a248958d7e4affba79aa3157e2c7b7@log.primeapps.io/13"
---
apiVersion: v1
data:
  aspnetapp.pfx: MIIEcgIBAzCCBDgGCSqGSIb3DQEHAaCCBCkEggQlMIIEITCCAxcGCSqGSIb3DQEHBqCCAwgwggMEAgEAMIIC/QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIkrrncSzDlUoCAggAgIIC0B/WII3vH0is31fWboRH4BfwLxqd+VvRqFZLK7Hno6dFdX3b7Aus8TpRPbCsI7qKITNz6YkP8ep8B9U4jOZUbSrRF5mpAOMwNaxiY/rwva3oz4wXOPo3QIEGqg+bqVVFOyjvckwe6u8O75okmPYEjaGXXXBOv2B5rt8Jaq06fC13ChTlBGlwAWDELLTjCVL1fo4+YmtC8FMsEhngMUvFvb0WfZd99fJmGOQHlbWaxiBlyVrjPHFxFzTcMmRi3hVCjbZm2xgbBCBZl0h8XTUaGyw5hPZ22j/SILyEAsqVK+/Xsvn3RBsd+FPpUnwFraNAAwNehpm2pLOEqA1RLgZgjvzTeaDdhrA+FpFhc/V3JJrBm0+YqbUFEArWKtFPrUUEj77kutZqgDcJs05pOeju3TQm6R2LRRGmnr+hlbz23HuS3ja3QAGNUUXiNeSggXBMecaz8PomIECaU2iF/7pWbguhSMP7JxCvw5+S7LgpNc5wpho6K5Si8tMlb7BzFjbdFoVYtc6agUB4bX/dn3ijWOobTUTkSLxyVzfNfyDJOUCo0RLChkHGJaBlEDBeJntxg2rF4IUTEdXPmz7G4ymudJ2u8Hg3sl4s/V+aqm5uR5ba72rZLB3Rs+bpgYomjuGRwkVev+v1EJd7FWSy99nMRwzR7EoXK9W59p8Ee5J6y3PM64VOmdB9cYMrd9G2PPSBhIRDkIiJdojGT+FEpjCrhmwEWOueWkXVa+I7tzRkJPkjSfRlPaGfNdEiXZDgD8stjmrLF6Wjg3/gX7+WkPuNNASuJ8xNhZEafhn100OnGCesCvXP6Tub3okEWMd5dAOyVq3r4XMqrSgVvQ6rj2LiorUFhk+K88cBGpI21/p0fonUrokFvC4O2PlTPwoPR1ytX57+7Vu8w+1t4vn4JbKSwqjY54KhfU0ZcD+83mBuT/dGWo8p3WV5VetrEItEaRvXTTCCAQIGCSqGSIb3DQEHAaCB9ASB8TCB7jCB6wYLKoZIhvcNAQwKAQKggbQwgbEwHAYKKoZIhvcNAQwBAzAOBAhY/tpYq9e7TwICCAAEgZBz/H0eL9NjxUiXUSXWRy9lPFpdQQKLSV4Lrp0EEuu/C7TlT6ttnr0ULmmXHhAEQhP6poZtLZHuyDdoU9PvNzBn5TDIgC2KuvCyVbIwTqhO6lLS6CR7qWl4gXVEMMmbw97bO3lx3QmyokNUnf3Pwd8ArIMACwgJvwi6VqDV/LZBSA9zMHX+bHa4kde6OVLEhjkxJTAjBgkqhkiG9w0BCRUxFgQURNjLA27hAeB2sl8e9HZmKMddxFowMTAhMAkGBSsOAwIaBQAEFNgHUQjP2Ck4YhSzOq0FoFEmhrlHBAjqW6pvvZTg8wICCAA=
kind: Secret
metadata:
  name: primeapps-app-test-selfsigned-ssl
  namespace: primeapps
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-app-test
  namespace: primeapps
  labels:
    k8s-app: "primeapps-app-test"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: primeapps-app-test
  template:
    metadata:
      labels:
        k8s-app: primeapps-app-test
    spec:
      volumes:
        - name: "self-signed-ssl"
          secret:
            secretName: primeapps-app-test-selfsigned-ssl
      containers:
        - name: primeapps-app-test
          image: primeapps/primeapps-app:1.19.211.1
          volumeMounts:
            - mountPath: "/etc/self-signed-ssl"
              name: self-signed-ssl
          env:
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /etc/self-signed-ssl/aspnetapp.pfx
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: PlatformDBConnection
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: RedisConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EnableJobs
            - name: AppSettings__EnableBpm
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EnableBpm
            - name: AppSettings__EnableRequestLogging
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EnableRequestLogging
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: EmailSMTPPassword
            - name: AppSettings__UseCdn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: UseCdn
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: HttpsRedirection
            - name: AppSettings__TestMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: TestMode
            - name: AppSettings__GoogleMapsApiKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: GoogleMapsApiKey
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-config-test
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-app-service-test
  namespace: primeapps
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-app-test
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-app-ingress-test
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |-
      add_header X-Robots-Tag "noindex, nofollow";
spec:
  tls:
    - hosts:
        - "*.test.primeapps.app"
      secretName: primeapps-test-wildcard-ssl
  rules:
    - host: "*.test.primeapps.app"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-app-service-test
              servicePort: 80
