---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-app-preview-config
  namespace: primeapps
data:
  TenantDBConnection: "server=db-pde.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=prod;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=db-pre.primeapps.io;port=5432;username=postgres;password=pr!m€Appsi0;database=platform;command timeout=0;keepalive=30;"
  RedisConnection: "cache.primeapps.io:6379,password=pr!m€Apps!0,defaultDatabase=1"
  StorageUrl: "https://storage.primeapps.io"
  StorageAccessKey: "47551d03d5524a4405c517aac418ef55"
  StorageSecretKey: "9983289d439f83dfe364b4e9884e9870"
  EnableJobs: "true"
  EnableRequestLogging: "false"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  UseCdn: "false"
  AuthenticationServerURL: "https://preview.primeapps.io"
  ClientId: "primeapps_preview"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  TestMode: "false"
  PreviewMode: "app"
  GoogleMapsApiKey: "AIzaSyDxai8Lo5_z03O9am5WyP5XvYtITzC_l-o"
  PreviewClient: "primeapps_preview"
  SentryDsn: "http://83071d88ebce45c290e44ee566d26d22@error.primeapps.io/16"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-app-preview
  namespace: primeapps
  labels:
    k8s-app: "primeapps-app-preview"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: primeapps-app-preview
  template:
    metadata:
      labels:
        k8s-app: primeapps-app-preview
    spec:
      imagePullSecrets:
        - name: gcr-pull-secret
      containers:
        - name: primeapps-app-preview
          image: gcr.io/primeapps/primeapps-app/debian:5.19.088.1
          env:
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: RedisConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EnableJobs
            - name: AppSettings__EnableRequestLogging
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EnableRequestLogging
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: EmailSMTPPassword
            - name: AppSettings__UseCdn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: UseCdn
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: HttpsRedirection
            - name: AppSettings__TestMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: TestMode
            - name: AppSettings__PreviewMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: PreviewMode
            - name: AppSettings__GoogleMapsApiKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: GoogleMapsApiKey
            - name: AppSettings__PreviewClient
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: PreviewClient
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-app-preview-config
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-app-preview-service
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-app-preview
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-app-preview-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - preview.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: preview.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-app-preview-service
              servicePort: 80