---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-auth-config
  namespace: primeapps
data:
  AuthDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=auth;command timeout=0;keepalive=30;"
  TenantDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=prod;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;"
  Authority: "https://auth.primeapps.io"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  ValidationSkipDomains: "localhost;primeapps.io;"
  StudioUrl: "https://studio.primeapps.io"
  GiteaEnabled: "true"
  GiteaUrl: "https://git.primeapps.io"
  PreviewMode: "tenant"
  SentryDsn: "https://b45f6285747c46cbbf76e3cb6470e9c4:749dc9a121ab44f890fed7fbb1010e84@log.primeapps.io/4"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-auth
  namespace: primeapps
  labels:
    k8s-app: "primeapps-auth"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: primeapps-auth
  template:
    metadata:
      labels:
        k8s-app: primeapps-auth
    spec:
      imagePullSecrets:
        - name: gcr-pull-secret
      containers:
        - name: primeapps-auth
          image: gcr.io/primeapps/primeapps-auth/debian:5.19.093.1
          env:
            - name: ConnectionStrings__AuthDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: AuthDBConnection
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: PlatformDBConnection
            - name: AppSettings__Authority
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: Authority
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: HttpsRedirection
            - name: AppSettings__ValidationSkipDomains
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: ValidationSkipDomains
            - name: AppSettings__StudioUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: StudioUrl
            - name: AppSettings__GiteaEnabled
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: GiteaEnabled
            - name: AppSettings__GiteaUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: GiteaUrl
            - name: AppSettings__PreviewMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: PreviewMode
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-auth-config
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-auth-service
  namespace: primeapps
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-auth
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-auth-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - auth.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: auth.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-auth-service
              servicePort: 80