apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: primeapps
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwcmltZWFwcHNhZG1pbiIsInBhc3N3b3JkIjoicHIhbeKCrEFwcHNpMGQiLCJlbWFpbCI6ImFkbWluQHByaW1lYXBwcy5pbyIsImF1dGgiOiJjSEpwYldWaGNIQnpZV1J0YVc0NmNISWhiZUtDckVGd2NITnBNR1E9In19fQ==
type: kubernetes.io/dockerconfigjson