---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-studio-config
  namespace: primeapps
data:
  TenantDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=prod;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=pre.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=platform;command timeout=0;keepalive=30;"
  StudioDBConnection: "server=pde.database.svc.cluster.local;port=5432;username=postgres;password=pr!m€Appsi0d;database=studio;command timeout=0;keepalive=30;"
  StorageUrl: "https://storage.primeapps.io"
  StorageAccessKey: "47059d03d1224a4505c517aaca18ef55"
  StorageSecretKey: "998321ed439a32dfc364b4e9884e9879"
  EnableJobs: "true"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  TestMode: "true"
  AuthenticationServerURL: "https://studio.primeapps.io"
  ClientId: "primeapps_studio"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  PreviewUrl: "https://preview.primeapps.io"
  KubernetesClusterRootUrl: "https://d5de4cad6841d39174e78377e1551f98.sk1.eu-west-1.eks.amazonaws.com"
  KubernetesClusterAccessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJla3MtYWRtaW4tdG9rZW4ta2ZxcGciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWtzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWNjODkyYjctNTRmZC0xMWU5LWFkZDMtMDYxMmIxOTc5YjIwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmVrcy1hZG1pbiJ9.j3rAlfrkjPiJxcleefpCF1P2E8oQNwvLe8ymW8sR_9N7QkTRRkyHLYVkvbGIL2gj-gzZ3itBeKoQ417VFn5LcybeE216ixxfHRIErnXZrTuatspSrIPM6D27VaBmUZLbYLkLZBW0SBKx0SBy8bJVmSu1LmiI-46d9cit4zmBZRYfrX0-WWq4uU0HUgo8D36dA5LC6_nnJ3xzbMs5VeyLPc3Z3UhQoDExcmxWUBDsbf3rvFQ85mj5rxXW0Y0JiHAHVKxKFrp3qidjlnikvFIZ905mpAyqmZksVZm4IOj5axX1gZ4eGLJRxPxrskNBZRM8PeAKxM6Gj1G8qgzkgj6b_Q"
  GiteaEnabled: "true"
  GiteaUrl: "http://git.primeapps.io"
  GiteaEmail: "primeapps"
  GiteaPassword: "pr!m€Appsi0g"
  GiteaDirectory: "/data/git/"
  SentryDsn: "https://a6d7a462d9184c5698ab07aa38b8a896:a915b64d63574d29b98998a69cbdc848@log.primeapps.io/2"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-studio
  namespace: primeapps
  labels:
    k8s-app: "primeapps-studio"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: primeapps-studio
  template:
    metadata:
      labels:
        k8s-app: primeapps-studio
    spec:
      volumes:
        - name: git-storage
          emptyDir: {}
      imagePullSecrets:
        - name: gcr-pull-secret
      containers:
        - name: primeapps-studio
          image: gcr.io/primeapps/primeapps-studio/debian:1.19.093.1
          env:
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__StudioDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StudioDBConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EnableJobs
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPassword
            - name: AppSettings__TestMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: TestMode
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: HttpsRedirection
            - name: AppSettings__PreviewUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PreviewUrl
            - name: AppSettings__KubernetesClusterRootUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterRootUrl
            - name: AppSettings__KubernetesClusterAccessToken
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterAccessToken
            - name: AppSettings__GiteaEnabled
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEnabled
            - name: AppSettings__GiteaUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaUrl
            - name: AppSettings__GiteaEmail
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEmail
            - name: AppSettings__GiteaPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaPassword
            - name: AppSettings__GiteaDirectory
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaDirectory
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-studio-service
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-studio
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-studio-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - studio.primeapps.io
      secretName: primeapps-wildcard-ssl
  rules:
    - host: studio.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-studio-service
              servicePort: 80