---
kind: ConfigMap
apiVersion: v1
metadata:
  name: primeapps-studio-config
  namespace: primeapps
data:
  TenantDBConnection: "server=db-pde.primeapps.io;port=5432;username=postgres;password=pr!meApp$!0;database=prod;command timeout=0;keepalive=30;"
  PlatformDBConnection: "server=db-pre.primeapps.io;port=5432;username=postgres;password=pr!meApp$!0;database=platform;command timeout=0;keepalive=30;"
  StudioDBConnection: "server=db-pde.primeapps.io;port=5432;username=postgres;password=pr!meApp$!0;database=studio;command timeout=0;keepalive=30;"
  StorageUrl: "https://storage.primeapps.io"
  StorageAccessKey: "47551d03d5524a4405c517aac418ef55"
  StorageSecretKey: "9983289d439f83dfe364b4e9884e9870"
  EnableJobs: "true"
  EmailSMTPEnableSsl: "true"
  EmailSMTPHost: "smtp.sendgrid.net"
  EmailSMTPPort: "587"
  EmailSMTPUser: "apikey"
  EmailSMTPPassword: "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"
  TestMode: "true"
  AuthenticationServerURL: "https://studio.primeapps.io"
  ClientId: "primeapps_studio"
  ClientSecret: "secret"
  ForwardHeaders: "true"
  HttpsRedirection: "true"
  PreviewUrl: "https://preview.primeapps.io"
  KubernetesClusterRootUrl: "https://30411da58524a8b8892dbdcc485de17f.yl4.eu-west-1.eks.amazonaws.com"
  KubernetesClusterAccessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJla3MtYWRtaW4tdG9rZW4taHRtN24iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWtzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzMyZWM4NWItMzZkNy0xMWU5LWE1OGMtMDY0NmE0OTYwYmE4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmVrcy1hZG1pbiJ9.VawsjvcvRMBMep-XkNyxhPT48j7yg9-an7QL7Hs-Q4oJ1Mejbor9H1m3G7rSukZx-bD9Tu5Qn46TPdLtm0Xy6edbMKMxpqV5IKWyDA1saAjZZZQRnyGKdIjZWapLSYqveZelgL361QYlllEFh5M9ObNAhbK6cIoZ_-dlUAVeLUFhNJe1lPs87QAvYiEXL8FQ1OuNPErCGnidET00INRGPzsCGAjFSfTDfTUdbjRVx6vZEc__Gw4lLdTb6WD_FSOoK2IozGJbK_m9tiFYqQFNPCqJoOBXXPreikoKWnuJAFudTC4zbJAw3Zw7JZdAknlOq7DOyNwGO58xl22HkD4mTw"
  GiteaEnabled: "true"
  GiteaUrl: "http://git.primeapps.io"
  GiteaEmail: "primeapps"
  GiteaPassword: "123456"
  GiteaDirectory: "/data/git"
  SentryDsn: "http://c3137bf4d2f54d1dab0ba16a32349ffa@error.primeapps.io/14"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: primeapps-studio
  namespace: primeapps
  labels:
    k8s-app: "primeapps-studio"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: primeapps-studio
  template:
    metadata:
      labels:
        k8s-app: primeapps-studio
    spec:
      volumes:
        - name: git-storage
          emptyDir: {}
      containers:
        - name: primeapps-studio
          image: gcr.io/primeapps/primeapps-studio/debian:1.19.084.3
          env:
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__StudioDBConnection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StudioDBConnection
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EnableJobs
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: EmailSMTPPassword
            - name: AppSettings__TestMode
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: TestMode
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: AuthenticationServerURL
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: HttpsRedirection
            - name: AppSettings__PreviewUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: PreviewUrl
            - name: AppSettings__KubernetesClusterRootUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterRootUrl
            - name: AppSettings__KubernetesClusterAccessToken
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: KubernetesClusterAccessToken
            - name: AppSettings__GiteaEnabled
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEnabled
            - name: AppSettings__GiteaUrl
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaUrl
            - name: AppSettings__GiteaEmail
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaEmail
            - name: AppSettings__GiteaPassword
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaPassword
            - name: AppSettings__GiteaDirectory
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: GiteaDirectory
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: primeapps-studio-config
                  key: SentryDsn
---
kind: Service
apiVersion: v1
metadata:
  name: primeapps-studio-service
spec:
  type: "ClusterIP"
  selector:
    k8s-app: primeapps-studio
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: primeapps-studio-ingress
  namespace: primeapps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - studio.primeapps.io
      secretName: primeapps-wildcard
  rules:
    - host: studio.primeapps.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: primeapps-studio-service
              servicePort: 80
# kind: Service
# apiVersion: v1
# metadata:
#   name: primeapps-studio-service
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:557655860736:certificate/5be35ad7-a512-4028-9fac-c4ca1e268080"
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
#     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
# spec:
#   type: "LoadBalancer"
#   selector:
#     k8s-app: primeapps-studio
#   ports:
#     - name: "http"
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: "https"
#       protocol: TCP
#       port: 443
#       targetPort: 80
