apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-app"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    k8s-app: "{{.Release.Name}}-app"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: "{{.Release.Name}}-app"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        k8s-app: "{{.Release.Name}}-app"
    spec:
      volumes:
        - name: "self-signed-ssl"
          secret:
            secretName: "{{.Release.Name}}-app-selfsigned-ssl"
      containers:
        - name: "{{.Release.Name}}-app"
          image: "primeapps/primeapps-app:{{.Values.image.tag}}"
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
          volumeMounts:
            - mountPath: "/etc/self-signed-ssl"
              name: self-signed-ssl
          env:
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /etc/self-signed-ssl/aspnetapp.pfx
            - name: ConnectionStrings__TenantDBConnection
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: TenantDBConnection
            - name: ConnectionStrings__PlatformDBConnection
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: PlatformDBConnection
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: RedisConnection
            - name: AppSettings__AuthenticationServerURL
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: AuthenticationServerURL
            - name: AppSettings__StorageUrl
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: StorageUrl
            - name: AppSettings__StorageAccessKey
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: StorageAccessKey
            - name: AppSettings__StorageSecretKey
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: StorageSecretKey
            - name: AppSettings__EnableJobs
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EnableJobs
            - name: AppSettings__EnableRequestLogging
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EnableRequestLogging
            - name: AppSettings__EmailSMTPEnableSsl
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EmailSMTPEnableSsl
            - name: AppSettings__EmailSMTPHost
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EmailSMTPHost
            - name: AppSettings__EmailSMTPPort
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EmailSMTPPort
            - name: AppSettings__EmailSMTPUser
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EmailSMTPUser
            - name: AppSettings__EmailSMTPPassword
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: EmailSMTPPassword
            - name: AppSettings__ClientId
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: ClientId
            - name: AppSettings__ClientSecret
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: ClientSecret
            - name: AppSettings__ForwardHeaders
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: ForwardHeaders
            - name: AppSettings__HttpsRedirection
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: HttpsRedirection
            - name: AppSettings__TestMode
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: TestMode
            - name: AppSettings__GoogleMapsApiKey
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: GoogleMapsApiKey
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-app-config
                  key: SentryDsn
      initContainers:
       - name: "{{.Release.Name}}-init"
         image: primeapps/primeapps-init:{{.Values.image.tag | trimSuffix "-debian" | trimSuffix "-centos" | trimSuffix "-redhat" }}
         imagePullPolicy: "{{.Values.image.pullPolicy}}"
         env:
            - name: CO_APISERVER_URL
              value: https://{{.Release.Name}}-pgo.{{.Release.Namespace}}.svc:8443
            - name: PGHOST
              value: {{.Values.postgresoperator.serverName}}.{{.Release.Namespace}}.svc
            - name: PGPASSWORD
              value: {{.Values.postgresoperator.password}}