apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-auth-service"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    k8s-app: "{{.Release.Name}}-auth"
spec:
  type: "ClusterIP"
  selector:
    k8s-app: "{{.Release.Name}}-auth" 
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80