apiVersion: v1
description: CrunchyData Postgres Operator Helm chart
name: postgresoperator
version: 0.3.2
appVersion: 3.5.2
keywords:
- postgres
- postgresql
- database
- sql
- operator
- crunchydata
home: https://www.crunchydata.com/
icon: http://trusted-charts-logos.stackpoint.io/crunchy_logo.png
sources:
- https://github.com/CrunchyData/postgres-operator
- https://github.com/CrunchyData/crunchy-containers
maintainers:
- url: https://www.crunchydata.com/
  email: info@crunchydata.com
