apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  ports:
    - port: {{.Values.authServicePort}}
      targetPort: {{.Values.authContainerPort}}
      protocol: TCP
      name: auth-http
    - port: {{.Values.appServicePort}}
      targetPort: {{.Values.appContainerPort}}
      protocol: TCP
      name: app-http
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"
#  type: {{ default "ClusterIP" .Values.serviceType | quote }}